### ISSUE TITLE
Please add 2 YO hosts to NXDN Hosts list

### ISSUE THREAD

**Issue by yo3cat** [g4klx/NXDNClients#104]
Good morning Jonathan

Please add the following two hosts to the NXDN Hosts list:

226 nxdn.dstar-yo.ro 41000 (Romania YO NXDN Network)
2263 nxdn.dstar-yo.ro 41000 (Bucharest YO3 NXDN Network)

Thank you for your help
Catalin (YO3CAT)

**Comment by g4klx** [comment]
Done
