### ISSUE TITLE
Log level issue

### ISSUE THREAD

**Issue by sp2ong** [g4klx/NXDNClients#119]
I setup in NXDNgateway.ini 

[Log]
DisplayLevel=0
FileLevel=2

but still exist unwanted lines type E:

M: 2020-10-06 15:33:37.966 Starting **NXDNGateway-20200824**
M: 2020-10-06 15:33:37.967 Linked at startup to reflector 65000
E: 2020-10-06 16:33:40.352 Cannot find address for host nxdn.digitalsicilia.it
I: 2020-10-06 16:33:43.010 Loaded 86 NXDN reflectors
E: 2020-10-06 16:33:43.011 Cannot find address for host 

The same problem exists in P25Gateway

M: 2020-10-07 06:12:40.123 Starting P25Gateway-**20200824**
M: 2020-10-07 06:12:40.123 Linked at startup to reflector 10400
E: 2020-10-07 07:12:46.381 Cannot find address for host p25.is0hha.hblink.it
I: 2020-10-07 07:12:48.820 Loaded 101 P25 reflectors
E: 2020-10-07 07:12:48.820 Cannot find address for host 
I: 2020-10-07 07:12:48.821 Loaded P252DMR (TG20)

73 Waldek

**Comment by g4klx** [comment]
It is working correctly.
The log levels are the lowest log level that will be logged, apart from 0 which is off. An E is higher than 2, so it is logged.


Sent from Yahoo Mail for iPhone


On Wednesday, October 7, 2020, 09:00, Waldek <notifications@github.com> wrote:




I setup in NXDNgateway.ini

[Log]

Logging levels, 0=No logging, 1=Debug, 2=Message, 3=Info, 4=Warning, 5=Error, 6=Fatal

DisplayLevel=0
FileLevel=2

but still exist unwanted lines type E:

M: 2020-10-06 15:33:37.966 Starting NXDNGateway-20200824
M: 2020-10-06 15:33:37.967 Linked at startup to reflector 65000
E: 2020-10-06 16:33:40.352 Cannot find address for host nxdn.digitalsicilia.it
I: 2020-10-06 16:33:43.010 Loaded 86 NXDN reflectors
E: 2020-10-06 16:33:43.011 Cannot find address for host

The same problem exists in P25Gateway

M: 2020-10-07 06:12:40.123 Starting P25Gateway-20200824
M: 2020-10-07 06:12:40.123 Linked at startup to reflector 10400
E: 2020-10-07 07:12:46.381 Cannot find address for host p25.is0hha.hblink.it
I: 2020-10-07 07:12:48.820 Loaded 101 P25 reflectors
E: 2020-10-07 07:12:48.820 Cannot find address for host
I: 2020-10-07 07:12:48.821 Loaded P252DMR (TG20)

73 Waldek

**Comment by sp2ong** [comment]
Thanks, it was my mistake to understand log level

**Comment by sp2ong** [comment]
But will be nice to have an order fo MMDVMHost, and xxxGateway programs:

Logging levels, 0=No logging, 1=Debug,  2=Warning,  3=Error, 4=Fatal,  5=Message, 6 = Info

The dashboard uses a log file to analyze data to display information base on M and I information log level below M and I  only when we need to find any problems. It is only my opinion

**Comment by g4klx** [comment]
No.
The numbering is based on severity; warning, error and fatal are more important than message or info. You want to see them, even if you don’t want any other logging.


Sent from Yahoo Mail for iPhone


On Wednesday, October 7, 2020, 10:19, Waldek <notifications@github.com> wrote:




But will be nice to have an order fo MMDVMHost, and xxxGateway programs:

Logging levels, 0=No logging, 1=Debug, 2=Warning, 3=Error, 4=Fatal, 5=Message, 6 = Info

The dashboard uses a log file to analyze data to display information base on M and I information log level below M and I only when we need to find any problems. It is only my opinion

**Comment by sp2ong** [comment]
Ok, thank you for the info, now I better understand log levels

73 Waldek
