### ISSUE TITLE
Add to list

### ISSUE THREAD

**Issue by SQ7PTE** [g4klx/NXDNClients#136]
Could you please add this to the list?

# 26079 NXDN Poland local Group Reflector
26079 nxdn-sp7.noip.pl 41400

Regards, SQ7PTE

**Comment by g4klx** [comment]
Done

**Comment by SQ7PTE** [comment]
Thank you Jonathan Naylor for your help.
Greetings.
SQ7PTE


sob., 12 gru 2020 o 14:37 Jonathan Naylor <notifications@github.com>
napisał(a):

**Comment by SQ7PTE** [comment]
Dear Jonathan.
Why can't you see the group 26079 Poland (26079 nxdn-sp7.noip.pl 41400) in the pi-star (HotSpot)
Did something happen? Were we not polite?
I am asking you for an answer.
greetings
Peter
SQ7PTE

**Comment by g4klx** [comment]
I am not responsible for Pi-Star. Please ask the maintainer of that package about it. If it’s in my file then it should appear in his eventually.


Sent from Yahoo Mail for iPhone


On Tuesday, February 16, 2021, 10:30, Piotr <notifications@github.com> wrote:




Dear Jonathan.
Why can't you see the group 26079 Poland (26079 nxdn-sp7.noip.pl 41400) in the pi-star (HotSpot)
Did something happen? Were we not polite?
I am asking you for an answer.
greetings
Peter
SQ7PTE

**Comment by SQ7PTE** [comment]
Jonathan.
Well. Thank you for your answer.

SQ7PTE


wt., 16 lut 2021 o 11:43 Jonathan Naylor <notifications@github.com>
napisał(a):
