### ISSUE TITLE
Please correct port information for NXDN Reflectors

### ISSUE THREAD

**Issue by yo3cat** [g4klx/NXDNClients#142]
Good afternoon,

I have found some errors on network ports for NXDN reflectors in Romania.

Please make sure they are as follows:
226 on port 41400
2263 on port 41403
2265 on port 41405

Thank you very much,
Catalin

**Comment by g4klx** [comment]
It would be far better if you could learn how to do pull requests so you can ensure that there is no mistakes made on addresses or ports.


Sent from Yahoo Mail for iPhone


On Monday, January 18, 2021, 11:01, Catalin Vatra <notifications@github.com> wrote:




Good afternoon,

I have found some errors on network ports for NXDN reflectors in Romania.

Please make sure they are as follows:
226 on port 41400
2263 on port 41403
2265 on port 41405

Thank you very much,
Catalin

**Comment by yo3cat** [comment]
You are right Jonathan... I really am sorry for the mistake.

 

This is the final change. 

 

If I have any changes in the future I will do pull requests.

 

Thank you very very much.

I really am sorry

Catalin

 

 

 

-----

’73 de YO3CAT

 

Vatra, Catalin Mihai

+40 (722) 514073

yo3cat@dstar-yo.ro

D-Star YO - Team

D-Star YO - Network Status

**Comment by yo3cat** [comment]
I have created a pull request
