### ISSUE TITLE
Please register NXDNReflector

### ISSUE THREAD

**Issue by hs2bmi** [g4klx/NXDNClients#170]
Hello G4KLX 

Please register NXDNReflector for my reflector.

TG = 822
Port = 41400
Reflector IP/Domain : nxdn.dstarthailand.com
TG822 XLX822 Thailand

Thank you very much.

de HS2BMI QUR'73 !!

**Comment by JA2CCV** [comment]
Please register NXDNReflector for my reflector.

TG = 44120
Port = 41400
Reflector IP/Domain : nxdn.owari.biz

Thank you very much.
de JA2CCV

**Comment by g4klx** [comment]
@JA2CCV Could you open a new issue for this please, and give more details of the new reflector, for example it's purpose.
