### ISSUE TITLE
New NXDN reflector

### ISSUE THREAD

**Issue by mikithd** [g4klx/NXDNClients#192]
I don't know if this is the right place but I ask, if nothing prevents, the registration of an NXDN reflector with the following data indicated in the attached file.

Thank you in advance.

[NXDNHosts.txt.txt](https://github.com/g4klx/NXDNClients/files/7402898/NXDNHosts.txt.txt)

**Comment by g4klx** [comment]
Can you give the new information you would like to add rather than give a new copy of the file. I don't have the time to compare your file to mine to find what the difference is.

**Comment by mikithd** [comment]
Ah OK. Excuse me.

Below are the indications of the new reflector to be added.

Thanks again ;)

[NXDN]
TG = 22488
Porta = 41400
IP = 185.203.119.229
TG 22488 Digital Network

**Comment by g4klx** [comment]
Done. Although a proper description of what the TG covers would probably increase the number of users.
