### ISSUE TITLE
Please register New NXDN Reflector 

### ISSUE THREAD

**Issue by hs3tdi** [g4klx/NXDNClients#197]
G4KLX , Please register NXDN Reflector

[NXDN]
TG = 52032
Port = 41404
IP = hs3as.pwk.ac.th
Surin Amateur Radio Association (HS3AS) ,Thailand,XLX149C

Thank you
de HS3TDI 73!!

**Comment by g4klx** [comment]
Donw

**Comment by hs3tdi** [comment]
I checked the domain name again. The status is normal now.
