### ISSUE TITLE
Please add NXDN TG 53099

### ISSUE THREAD

**Issue by ZL2AUS** [g4klx/NXDNClients#22]
Can you please add NXDN TG 53099 this is a NXDN reflector in New Zealand mainly for NZ use and is currently bridged to BM TG 53099

53099  203.86.206.49  41000

**Comment by g4klx** [comment]
I've added it, but shouldn't you be using port 41400?

**Comment by ZL2AUS** [comment]
Sorry Jonathan my typing error .. it is port 41400

At 01:57 AM 10/01/2019, you wrote:

**Comment by g4klx** [comment]
Fixed.
