### ISSUE TITLE
Please register NXDNReflector Server

### ISSUE THREAD

**Issue by JA2CCV** [g4klx/NXDNClients#222]
Hello.
I must sincerely apologize.

Could you please add NXDN Reflector to Hosts file?
[NXDN]
TG = 44120
Port = 41400
IP-Domain= nxdn.owari.biz

Thank you.  
de JA2CCV  73'

**Comment by g4klx** [comment]
Hi
Sorry, what I meant was could you provide more details of what your reflector is for? If you look at the other reflectors in the NXDNHosts.txt file, you will see that each has a description about its use. Could you do the same for yours please.
Jonathan  G4KLX

    On Monday, 20 June 2022, 03:25:31 BST, Y.Kawaguchi ***@***.***> wrote:  
 
 


Hello.
I must sincerely apologize.

Could you please add NXDN Reflector to Hosts file?
[NXDN]
TG = 44120
Port = 41400
IP-Domain= nxdn.owari.biz

Thank you.
de JA2CCV 73'

**Comment by JA2CCV** [comment]
Hello.

Sorry to trouble you.
I would like to configure the reflectors(XLX,YSF,M17) and bridges that I manage.
thank you.

de JA2CCV Yoichi

**Comment by g4klx** [comment]
Added
Jonathan  G4KLX

    On Tuesday, 21 June 2022, 07:03:36 BST, Y.Kawaguchi ***@***.***> wrote:  
 
 


Hello.

Sorry to trouble you.
I would like to configure the reflectors(XLX,YSF,M17) and bridges that I manage.
thank you.

de JA2CCV Yoichi
