### ISSUE TITLE
NXDN Reflector Modify Request for TG#46010

### ISSUE THREAD

**Issue by bh1nyr** [g4klx/NXDNClients#224]
Hello g4klx,

Due to problem of DNS, I would like to modify the address of NXDN reflector TG#46010 as follow:

[NXDN]
TG = 46010
Port = 41400
IP = 101.89.136.112
NXDN XLX074 Modules A / BM TG46010

Thanks in advance!

vy 73!
de BH1NYR

**Comment by g4klx** [comment]
Done
