### ISSUE TITLE
List of NXDN Host name in Pi-star config

### ISSUE THREAD

**Issue by iu2kul** [g4klx/NXDNClients#226]
Hi there,

I,' IU2KUL manager of 65100 NXDN Reflector.

we have notest that on NXDN List on Pi-Star config, after some latest update, it is not possibile to select TG over 65000 .... so some reflector are out of config.

are you aware about this problem ? It is possible to solve it ? At this moment the only work around is about filling manuall the HOSTSname.txt file and then doing udate.

Thanks for your attention

Kind regards
IU2KUL - op. Franco

**Comment by g4klx** [comment]
Pi-Star is a separate piece of software to the MMDVM and it's various gateways. Could you raise it on a Pi-Star forum and see what the response is.

**Comment by iu2kul** [comment]
Hi Jonathan,


thanks for your reply. I will put issu on Pi-star forum

73

Il 28/06/2022 22:14, Jonathan Naylor ha scritto:
