### ISSUE TITLE
Update NXDNHosts.txt

### ISSUE THREAD

**Issue by kk6rq** [g4klx/NXDNClients#263]
Hi, can you add my new NXDN Reflector,  please?
(Also if you wouldn't mind validating my tabs are not spaces!)

Thanks,

Bob
KK6RQ

ps. Sorry should have been a pull request (did it on my phone @ 5AM)

# 11069 KK6RQ's NXDN Reflector
11069	area52.zapto.org 41400

**Comment by F1PTL** [comment]
Update server NXDN France 65208
# 65208 French-NXDN
65208	nxdn.f5dan.fr  41400

**Comment by g4klx** [comment]
Done

**Comment by kk6rq** [comment]
Sorry, maybe I haven't waited long enough for the update to show; I see the french person's reflector (who isn't me, not sure why you sent me their info); I'm 11069, not 65208.

Robert Gaynor
KK6RQ

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kk6rq** [comment]
Disregard, I see it as updated on github; evidently hasn't dl'd to me yet.

Thanks,

Bob
KK6RQ

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
