### ISSUE TITLE
change of my ddns account 

### ISSUE THREAD

**Issue by sv2snh** [g4klx/NXDNClients#266]
https://github.com/g4klx/NXDNClients/blob/0c163b34374f10ea7ad2de6b783ba771ee7d3df7/NXDNGateway/NXDNHosts.txt#L211
Please change my ddns account from nxdn-frn.ddns.net   to the correct greece-frn.ddns.net  port 41400 due to new network configuration.Thx 73.

**Comment by g4klx** [comment]
Done

**Comment by sv2snh** [comment]
Hi Jonathan thanks for your time  Στάλθηκε από την Αλληλογραφία για τα Windows Από: Jonathan NaylorΑποστολή: Κυριακή, 15 Ιανουαρίου 2023 5:45 μμΠρος: g4klx/NXDNClientsΚοιν.: SAKIS; AuthorΘέμα: Re: [g4klx/NXDNClients] change of my ddns account (Issue #266) Closed #266 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
