### ISSUE TITLE
Adding TG 31188

### ISSUE THREAD

**Issue by umj** [g4klx/NXDNClients#28]
Johnathon could you please add TG 31188 to the NXDN list, We cover the southern half of Indiana with NXDN as well as the other mmdvm modes , we have been converting unused or under utilized repeaters into mmdvm repeaters and have recently purchased 50 Tait mobiles to used as mobile and high power hotspots for poor coverage areas in the hilly south of Indiana. And will be adding mmdvm repeaters as a link to all of the major Universities in Indiana as part of the Southern Indiana Network.
Please condsider this request.
31188 w9windigital.org 41400
 73 de Rick Nicholson / N9UMJ

**Comment by g4klx** [comment]
Done
