### ISSUE TITLE
Please add NXDN TG

### ISSUE THREAD

**Issue by W3KIT-910** [g4klx/NXDNClients#298]
Hello, 

Am I doing this the right way?

Please submit 137 to the NXDN host list.

137 nxdn137.mywire.org 41400

Thailand - USA XLX Bridge

Thank you so much,

Kit

**Comment by W3KIT-910** [comment]
I used to request the TG this way or there is a new / another way to request.

Thanks,
Kit

**Comment by g4klx** [comment]
Hi Kit
Ideally your requests should be done as pull requests which I can merge in a couple of key presses. With requests like this, I have to do them manually, and sometime I don't get around to it for a while.
Jonathan

    On Sunday, 2 April 2023 at 17:46:03 BST, W3KIT-910 ***@***.***> wrote:  
 
 


Hello,

Am I doing this the right way?

Please submit 137 to the NXDN host list.

137 nxdn137.mywire.org 41400

Thailand - USA XLX Bridge

Thank you so much,

Kit

**Comment by g4klx** [comment]
Done
