### ISSUE TITLE
Change of NXDNReflectors Domain Names in the NXDNHosts.txt file

### ISSUE THREAD

**Issue by Iantull** [g4klx/NXDNClients#3]
Please update the NXDNHosts.txt file in the NXDNGateway,
1200     florida.nxref.org     41400
10400   pacific.nxref.org    41400

**Comment by g4klx** [comment]
I did it locally on mine last night (UK time) just after you sent me the email about it, and then forgot to push it to GitHub. Done now. My bad.

**Comment by Iantull** [comment]
Thanks

Regards
Ian (VK2HK)

Typo's, autocorrect or spelling mistakes courtesy of both myself and my iPhone
