### ISSUE TITLE
Updating NXDN Hosts file IP Address for reflector 26200

### ISSUE THREAD

**Issue by dk6px** [g4klx/NXDNClients#332]
Hi all, Hi Jonathan,
caused by nomore use and nomore interest in running this reflector by marco [https://do0sre.de/nxdn-idas-germany]

I (dk6px) want to takeover NXDN Reflector 26200 for germany

webaddress for reflector 26200
https://nxdn262.ddns.net/
port 41400

will set it up when confirmed
kind regards Stefan dk6px

**Comment by g4klx** [comment]
It would have been nice if the original owner had told me. I can only update the file once I know the new IP address or hostname for the reflector.

**Comment by dk6px** [comment]
Hi Jonathan
Hostname will be nxdn262.ddns.net as noticed

Marco, ok for your??
Kind regards, thank you for your service
Kind regards
Stefan

Jonathan Naylor ***@***.***> schrieb am Di., 28. Nov. 2023,
17:53:

**Comment by g4klx** [comment]
Done
