### ISSUE TITLE
Reflector NXDX numbering change

### ISSUE THREAD

**Issue by mikithd** [g4klx/NXDNClients#359]
Hi Jonathan, I'm saddened by this new communication I'm making to you but, recently I was assigned a new TG DMR and, following this change (which was well-liked among other things), I would like to standardize the numbering of the various reflectors connected to the network multi-protocol that I manage.

for the above, I ask you to replace the following reflector:

.# 22487 Italy Centro - Digiland
22487  217.160.155.85  41400

with the following new numbering:

.# 22208 Italy Centro - Digiland
22208  217.160.155.85  41400

I await your notification to proceed with the adaptation of the reflector in my possession.

In apologizing for this umpteenth change request, I thank you in advance and best regards.

IZ0THD, Michele

**Comment by g4klx** [comment]
Done
