### ISSUE TITLE
Inactive TG Server — Procedure for Changing Host?

### ISSUE THREAD

**Issue by s1lviu** [g4klx/NXDNClients#368]
Hi @g4klx and thank you for your continuous contributions!

I am considering changing the host for an [existing TG](https://github.com/g4klx/NXDNClients/blob/master/NXDNGateway/NXDNHosts.txt#L46) due to the current server being offline. 

Could you please advise on the process or considerations for making such a change? I want to ensure that this aligns with the project’s standards and avoids any potential disagreements within the community.

Thank you in advance for your guidance!

Best regards,
Silviu YO6SAY

**Comment by g4klx** [comment]
Hi Silviu

Just do a PR or add the new address/port onto this message.

Jonathan  G4KLX

**Comment by s1lviu** [comment]
Done, @g4klx - https://github.com/g4klx/NXDNClients/pull/369
Thanks
