### ISSUE TITLE
add my reflector  PU2RRY 

### ISSUE THREAD

**Issue by PU2RRY** [g4klx/NXDNClients#399]
[NXDNHosts.txt](https://github.com/user-attachments/files/17272254/NXDNHosts.txt)

**Comment by g4klx** [comment]
I'm sorry I need a properly formatted Pull Request or a simple readable description of the new NXDN that you need. Just attaching a new file is not acceptable.

**Comment by PU2RRY** [comment]
Sorry friend, here is the correct format only:

# 7246  Brasil Multiprotocolo 
7246	pu2rry.com.br		41400

**Comment by PU2RRY** [comment]
hello ?
