### ISSUE TITLE
Add a node please

### ISSUE THREAD

**Issue by wspivak** [g4klx/NXDNClients#414]
Can you add to the host file:

Server      sbanetweb.com:41400
    Dash    https://sbanetweb.com:8080
    TG      11710

Thank you and Happy Thanksgiving and have a nice holiday season.

Wayne, KC2NJV

**Comment by wspivak** [comment]
Hi,

Yes, it is for use by members of both my local Emergency Communications Team and the greater national teams, as well as the public to practice and or use as an avenue to communicate across the spectrum of Ham modalities.

**Comment by g4klx** [comment]
Done

**Comment by wspivak** [comment]
Thank you.
