### ISSUE TITLE
Please add new NXDN Reflector.

### ISSUE THREAD

**Issue by R1IK-Yakov** [g4klx/NXDNClients#47]
# 2503 RU DMR TG2503
2503 nxdn.r1ik.ru 41400

**Comment by R1IK-Yakov** [comment]
This is a permanent link in DMR TG2503.

**Comment by g4klx** [comment]
Could you turn this into a merge request please?

**Comment by R1IK-Yakov** [comment]
Done! Waiting for when You add my NXDN and P25 reflectors.

 

https://github.com/g4klx/P25Clients/pull/64

https://github.com/g4klx/NXDNClients/pull/52
