### ISSUE TITLE
Add new listing to NXDN host file

### ISSUE THREAD

**Issue by WA3PNY** [g4klx/NXDNClients#70]
Could you please add the following listings to the NXDN host file:

31425 70.44.20.24:41400 XLX545A Pennsylvania Cross Mode
  545   70.44.20.24:41401  XLX545E PA NXDN

Many thanks,
Jeff

**Comment by g4klx** [comment]
Done

**Comment by WA3PNY** [comment]
Thank you very much

Jeff

Jeffrey V. Bauer
6381 Mulberry Ln.
Macungie, PA 18062
WA3PNY
CCS-7 3142263
NXDN 504
Wires-X 18394/28394
