### ISSUE TITLE
Req to add German NXDN TG26200

### ISSUE THREAD

**Issue by dk6px** [g4klx/NXDNClients#79]
Thanks Jonathan
PSE add 26200 ,  http://26200.ham-nxdn.de/  41400
Vy73 Stefan dk6px

**Comment by g4klx** [comment]
Done

**Comment by dk6px** [comment]
Thank you Jonathan for your serviceAm 09.03.20, 12:10 schrieb Jonathan Naylor <notifications@github.com>:

  Done
