### ISSUE TITLE
NXDN 25000

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/NXDNClients#81]
@awasser1 @g4klx 
NXDN Host 25000 was added in this commit: https://github.com/g4klx/NXDNClients/commit/afbead101e91b27ae4c17e2b18d4f68be3175456#diff-230f77d7c7ae0a4c21f07d16b716c7e9 by @awasser1 back in August 2018.

I have been contacted by Tony NN1D to tell me that he owns NX Core 25000 and he has already previously tried to pull a request to replace this host.

I'm not sure what the history is here, just trying to help us all work it out.

The current entry in the host file looks like this:

# CT NXCore, 25000
25000	45.62.211.216	41425

The proposed change looks like this:

# NX Core, 25000
25000    173.166.94.77     41400

**Comment by g4klx** [comment]
Hi Andy

I don't remember a pull request from him, but that may be my memory.

I've updated the host file as requested and I hope that is sufficient. I wonder what the original entry pointed to?

Jonathan  G4KLX

**Comment by AndyTaylorTweet** [comment]
Jonathan,

This was the request from Tony: https://github.com/g4klx/NXDNClients/pull/77
I can see that you accepted that, but bizarrely it vanished again, maybe a roll back or some thing, not sure about that.

Thank you for taking a look at this, I'm sure @NN1D will be pleased :)
